# Generated by Django 5.2.1 on 2025-10-16 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_chatmessage_userpreference_chatanalytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatanalytics',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['user', 'date'], name='chatbot_cha_user_id_2059e4_idx'),
        ),
    ]
